version: '3.8'

services:
  mongo:
    image: mongo:6.0
    container_name: dth-mongo
    ports:
      - "27017:27017"

  app:
    build: .
    image: dth-app-image
    container_name: dth-app
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    environment:
      - SPRING_DATA_MONGODB_HOST=mongo
      - SPRING_DATA_MONGODB_PORT=27017
