package com.example.SpringBoot.Enums;

public class LocationEnums {
	public enum State {
		// Indian States
		ANDHRA_PRADESH, ARUNACHAL_PRADESH, ASSAM, BIHAR, CHHATTISGARH, GOA, GUJARAT, HARYANA, HIMACHAL_PRADESH,
		JHARKHAND, KARNATAKA, KERALA, MADHYA_PRADESH, MAHARASHTRA, MANIPUR, MEGHALAYA, MIZORAM, NAGALAND, ODISHA,
		PUNJAB, RAJASTHAN, SIKKIM, TAMIL_NADU, TELANGANA, TRIPURA, UTTAR_PRADESH, UTTARAKHAND, WEST_BENGAL,

		// Union Territories
		ANDAMAN_AND_NICOBAR_ISLANDS, CHANDIGARH, DADRA_AND_NAGAR_HAVELI_AND_DAMAN_AND_DIU, DELHI, JAMMU_AND_KASHMIR,
		LADAKH, LAKSHADWEEP, PUDUCHERRY
	}

	public enum Country {
		INDIA,
	}

	public enum Gender {
		MALE, FEMALE, OTHER
	}

	public enum IdProofType {
		AADHAAR, PASSPORT, PAN, VOTER_ID, DRIVER_LICENSE
	}

	public enum SetupBoxType {
		HD, SD, DVR
	}

	public enum Status {
		ACTIVE, INACTIVE, BLOCKED
	}
}
